//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrimeraAplicacionOfficial_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGIN
    {
        public int ID { get; set; }
        public string USER { get; set; }
        public string PASS { get; set; }
        public Nullable<int> HABILITADO { get; set; }
    }
}
