//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrimeraAplicacionOfficial_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROL_PAGINA
    {
        public int IDROLPAGINA { get; set; }
        public Nullable<int> IDROL { get; set; }
        public Nullable<int> IDPAGINA { get; set; }
        public Nullable<int> HABILITADO { get; set; }
    
        public virtual PAGINA PAGINA { get; set; }
        public virtual ROL ROL { get; set; }
    }
}
